### ISSUE TITLE
Does Quaternion addition have a (useful) meaning?

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/hektor#79]
Seriously, I don't know, I want a math expert to tell me.

I think the answer is "no", but I want someone who spent more than 3 minutes googling it to give a more definitive answer.

**Comment by icefoxen** [comment]
No*

(*) maybe

**Comment by Lokathor** [comment]
So, [wikipedia](https://en.wikipedia.org/wiki/Quaternion#Definition) shows that you _can do_ component-wise addition, but I don't know how to describe that operation.

Ralith noted on Discord that "quaternions in math in general" are a superset of "quaternions used as rotations". We mostly want them for rotations, so until someone can tell me if addition is somehow sane for rotation quaternions this will just sit open I guess.

**Comment by icefoxen** [comment]
Nah, just close the issue until someone presents a reason to add it.

**Comment by Lokathor** [comment]
I want a quaternion expert to magically swoop in an tell me the lore ;_;

**Comment by Lokathor** [comment]
This basic tutorial thingy here shows that you want an addition function in your quaternion class, but doesn't say why on that page or the other pages I saw

https://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/code/index.htm
